import React from 'react'

const About = () => {
    return (
        <div className='about'>
            <div className='abt-1-blk'>
                <h1>Who we are</h1>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Delectus temporibus consequuntur tempora mollitia dolor dolorem esse impedit consectetur placeat recusandae corrupti veritatis itaque blanditiis quod expedita explicabo voluptates optio, incidunt ab natus autem laudantium? Dignissimos nulla cumque tenetur sit labore sint iusto reprehenderit dolor deleniti laborum quibusdam facere quae possimus voluptas expedita ut dicta quam, nisi est excepturi ratione ullam, odio in repellat. Commodi natus minus harum maiores. Quidem veritatis nam quae voluptates, voluptatem ab. Labore officia quaerat eum ratione nam, necessitatibus iste nesciunt optio excepturi molestiae debitis! Quibusdam debitis enim laboriosam necessitatibus voluptatum nulla quidem voluptates rem recusandae omnis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam velit, sunt exercitationem corrupti architecto quisquam repudiandae dolores veritatis voluptate, repellendus porro suscipit quod eos hic assumenda. Similique, id quo sint amet omnis, deserunt sed aliquid, assumenda cumque sunt doloremque tempora nihil corrupti quod vel placeat! Ipsa nesciunt, recusandae eaque quis minus beatae voluptatum consectetur provident sit modi repellat, perferendis magni? Dolor beatae eveniet, assumenda distinctio doloribus necessitatibus ab temporibus doloremque numquam repellat eius libero itaque sequi in dolorum. Impedit quod nisi neque pariatur quaerat et cumque, minus deserunt accusamus ratione tenetur, ipsum earum repellendus dolore soluta, laborum qui magnam quidem? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Non aspernatur, excepturi similique iste beatae distinctio, nulla fugit quam nesciunt praesentium atque magni voluptas inventore obcaecati et deserunt consequatur earum qui veniam eligendi corporis repellat quis. Qui sit consectetur illum blanditiis repellendus amet, esse, repellat ipsum dolores ea, architecto quisquam natus.</p>
            </div>
            <div className="abt-2-blk">
                <h1>Our Speciality</h1>
                <div className="speciality-block">
                    <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis soluta vitae dolorem blanditiis atque impedit reprehenderit numquam tempore, fugit ea eum iste quaerat error ipsam modi, quo suscipit, doloremque magnam ducimus. Cum dolorem iure autem sequi! Dignissimos quod, illo nobis aliquam adipisci consequuntur obcaecati temporibus et est aliquid pariatur laborum deleniti perspiciatis. Dicta optio iste quisquam, aliquam, tempora harum alias autem ipsam quasi aliquid ex sed nihil porro. Molestias nulla maiores doloribus, beatae sapiente, enim commodi natus consequatur fugiat sunt nobis cupiditate placeat ipsam hic harum quas id doloremque corporis nemo tenetur reprehenderit. Sint obcaecati incidunt optio perspiciatis rem ea? Lorem ipsum, dolor sit amet consectetur adipisicing elit. Excepturi delectus voluptas, quo consequatur quia error. Perspiciatis quisquam voluptatum, est itaque officiis ex atque, quam aperiam debitis fugiat neque! Aperiam quod vel similique unde nisi facilis eos aspernatur iste minima possimus? Molestias placeat quisquam rem a et repellat, cupiditate totam ex nemo aliquid eum aliquam sit distinctio, fugiat iste, amet sed architecto quaerat nam! Dolore sed tenetur cum. Reiciendis nulla expedita tempore labore dolore, rem placeat deserunt aliquam consectetur commodi aspernatur animi itaque quae ex quidem veritatis cumque optio accusamus et voluptas delectus ullam doloribus? Repudiandae officiis cum ipsam fuga iste!</p>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque, tempora. Ipsa magnam explicabo debitis voluptas vitae nemo harum sunt, mollitia quibusdam exercitationem inventore pariatur facilis. Sequi non voluptate, consequuntur est eum ipsa quia quo impedit fugit deserunt. Illo assumenda esse, sint eligendi architecto rerum pariatur commodi aperiam quasi, voluptatibus nemo iusto repellat, at impedit accusamus. Itaque nihil quis, aut accusantium ipsa tempora natus, excepturi delectus culpa veritatis iusto esse aliquam nobis ipsum? Nostrum vero ea fugit, commodi quam quia placeat similique assumenda dolore earum aut ducimus aliquam nisi ad in architecto reprehenderit, sit beatae officia ab quos? Mollitia, inventore ab! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, voluptate, architecto earum impedit rem quibusdam pariatur, esse commodi dolor perspiciatis harum doloremque quia animi! Obcaecati optio, quia ab possimus sint neque quae, quaerat tempora voluptatum exercitationem libero doloremque non corrupti quas officia aliquid quis. Asperiores sed, commodi voluptatem maiores autem ex recusandae aut placeat, quo eveniet laboriosam fuga, rerum nostrum velit suscipit! Doloribus fugiat perspiciatis natus! Sunt, molestias possimus quam omnis repellat laboriosam vero incidunt, perspiciatis doloremque, dolor et quis vel quo quia ipsa reiciendis distinctio sint eligendi? Unde cum sed accusantium adipisci autem iusto neque maxime doloremque, vitae repudiandae.</p>
                </div>
            </div>
            <div className="abt-3-blk">
                <h1>Our Chief</h1>
                <div className="cheif-block">
                    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eos et rem id culpa incidunt delectus consectetur voluptas commodi est ea veniam tempora ad repellat perspiciatis doloremque minima suscipit enim dolorem nemo, corporis nulla harum quidem sunt. Molestiae quas, voluptate, numquam est beatae alias nesciunt et fugit dolores tempore incidunt, placeat illum quod vel aperiam vero voluptatibus in sit labore fuga officia! Quia sit reprehenderit vero natus voluptates harum sed iure, eveniet similique quasi, a animi exercitationem tempore quidem. Recusandae iure totam fugit dolorum eius rem at repellendus est, enim sint, necessitatibus nostrum distinctio! Modi, atque ab recusandae distinctio eaque repudiandae.</p>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque at recusandae, aperiam iste corrupti ducimus inventore perspiciatis. Consequatur, doloribus nam consequuntur atque vitae, esse reiciendis consectetur veritatis alias adipisci enim iste, asperiores nihil ducimus! Repellat, soluta. Doloremque, tempora necessitatibus voluptas laboriosam vitae aperiam neque fugiat labore facilis nemo eum nam tempore facere accusamus in earum distinctio assumenda deserunt error consequuntur. Quibusdam alias assumenda autem ipsam debitis aliquid, quas, sapiente aspernatur necessitatibus soluta ducimus illo rerum! Minus atque odio nam neque perferendis, in ea sapiente! Nam nostrum incidunt quo nisi, facilis ipsum quia fugit cum inventore dicta dolores doloremque est numquam!</p>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque at recusandae, aperiam iste corrupti ducimus inventore perspiciatis. Consequatur, doloribus nam consequuntur atque vitae, esse reiciendis consectetur veritatis alias adipisci enim iste, asperiores nihil ducimus! Repellat, soluta. Doloremque, tempora necessitatibus voluptas laboriosam vitae aperiam neque fugiat labore facilis nemo eum nam tempore facere accusamus in earum distinctio assumenda deserunt error consequuntur. Quibusdam alias assumenda autem ipsam debitis aliquid, quas, sapiente aspernatur necessitatibus soluta ducimus illo rerum! Minus atque odio nam neque perferendis, in ea sapiente! Nam nostrum incidunt quo nisi, facilis ipsum quia fugit cum inventore dicta dolores doloremque est numquam!</p>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque at recusandae, aperiam iste corrupti ducimus inventore perspiciatis. Consequatur, doloribus nam consequuntur atque vitae, esse reiciendis consectetur veritatis alias adipisci enim iste, asperiores nihil ducimus! Repellat, soluta. Doloremque, tempora necessitatibus voluptas laboriosam vitae aperiam neque fugiat labore facilis nemo eum nam tempore facere accusamus in earum distinctio assumenda deserunt error consequuntur. Quibusdam alias assumenda autem ipsam debitis aliquid, quas, sapiente aspernatur necessitatibus soluta ducimus illo rerum! Minus atque odio nam neque perferendis, in ea sapiente! Nam nostrum incidunt quo nisi, facilis ipsum quia fugit cum inventore dicta dolores doloremque est numquam!</p>

                </div>
            </div>
        </div>
    )
}

export default About;