import React from 'react';
import { Link } from 'react-router-dom';

const Policy = () => {
    return (
        <div className='policy'>
        <div className="policy-content">
            <h2>Terms And Policy</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit maiores excepturi nemo, rerum in animi.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, iste quidem asperiores accusantium aliquam, placeat dolore vero at quibusdam sapiente ab voluptatibus, quaerat laborum quos rem? Sunt ducimus fuga doloribus nulla cum provident illum sint at quaerat nisi asperiores consectetur blanditiis atque excepturi reprehenderit vitae, est temporibus ut veritatis voluptas illo quibusdam deserunt. Ipsa voluptate rerum, repellendus dicta placeat ab quisquam vero unde laboriosam quod fugiat, cupiditate praesentium odit impedit non, magnam consequatur. Libero tempore enim ducimus explicabo similique possimus non, aspernatur tempora hic dolorum, dolore nihil at quisquam illo mollitia omnis consequuntur doloribus animi consequatur eos obcaecati facere dolores.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit maiores excepturi nemo, rerum in animi.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, iste quidem asperiores accusantium aliquam, placeat dolore vero at quibusdam sapiente ab voluptatibus, quaerat laborum quos rem? Sunt ducimus fuga doloribus nulla cum provident illum sint at quaerat nisi asperiores consectetur blanditiis atque excepturi reprehenderit vitae, est temporibus ut veritatis voluptas illo quibusdam deserunt. Ipsa voluptate rerum, repellendus dicta placeat ab quisquam vero unde laboriosam quod fugiat, cupiditate praesentium odit impedit non, magnam consequatur. Libero tempore enim ducimus explicabo similique possimus non, aspernatur tempora hic dolorum, dolore nihil at quisquam illo mollitia omnis consequuntur doloribus animi consequatur eos obcaecati facere dolores.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit maiores excepturi nemo, rerum in animi.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, iste quidem asperiores accusantium aliquam, placeat dolore vero at quibusdam sapiente ab voluptatibus, quaerat laborum quos rem? Sunt ducimus fuga doloribus nulla cum provident illum sint at quaerat nisi asperiores consectetur blanditiis atque excepturi reprehenderit vitae, est temporibus ut veritatis voluptas illo quibusdam deserunt. Ipsa voluptate rerum, repellendus dicta placeat ab quisquam vero unde laboriosam quod fugiat, cupiditate praesentium odit impedit non, magnam consequatur. Libero tempore enim ducimus explicabo similique possimus non, aspernatur tempora hic dolorum, dolore nihil at quisquam illo mollitia omnis consequuntur doloribus animi consequatur eos obcaecati facere dolores.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit maiores excepturi nemo, rerum in animi.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, iste quidem asperiores accusantium aliquam, placeat dolore vero at quibusdam sapiente ab voluptatibus, quaerat laborum quos rem? Sunt ducimus fuga doloribus nulla cum provident illum sint at quaerat nisi asperiores consectetur blanditiis atque excepturi reprehenderit vitae, est temporibus ut veritatis voluptas illo quibusdam deserunt. Ipsa voluptate rerum, repellendus dicta placeat ab quisquam vero unde laboriosam quod fugiat, cupiditate praesentium odit impedit non, magnam consequatur. Libero tempore enim ducimus explicabo similique possimus non, aspernatur tempora hic dolorum, dolore nihil at quisquam illo mollitia omnis consequuntur doloribus animi consequatur eos obcaecati facere dolores.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit maiores excepturi nemo, rerum in animi.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, iste quidem asperiores accusantium aliquam, placeat dolore vero at quibusdam sapiente ab voluptatibus, quaerat laborum quos rem? Sunt ducimus fuga doloribus nulla cum provident illum sint at quaerat nisi asperiores consectetur blanditiis atque excepturi reprehenderit vitae, est temporibus ut veritatis voluptas illo quibusdam deserunt. Ipsa voluptate rerum, repellendus dicta placeat ab quisquam vero unde laboriosam quod fugiat, cupiditate praesentium odit impedit non, magnam consequatur. Libero tempore enim ducimus explicabo similique possimus non, aspernatur tempora hic dolorum, dolore nihil at quisquam illo mollitia omnis consequuntur doloribus animi consequatur eos obcaecati facere dolores.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit maiores excepturi nemo, rerum in animi.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, iste quidem asperiores accusantium aliquam, placeat dolore vero at quibusdam sapiente ab voluptatibus, quaerat laborum quos rem? Sunt ducimus fuga doloribus nulla cum provident illum sint at quaerat nisi asperiores consectetur blanditiis atque excepturi reprehenderit vitae, est temporibus ut veritatis voluptas illo quibusdam deserunt. Ipsa voluptate rerum, repellendus dicta placeat ab quisquam vero unde laboriosam quod fugiat, cupiditate praesentium odit impedit non, magnam consequatur. Libero tempore enim ducimus explicabo similique possimus non, aspernatur tempora hic dolorum, dolore nihil at quisquam illo mollitia omnis consequuntur doloribus animi consequatur eos obcaecati facere dolores.</p>

        </div>
        </div>
    )
}

export default Policy
